c= [(-thetadot^2*(Jz-Jy)*sin(phi)*cos(phi) + psidot^2*(Jz-Jy)*sin(phi)*cos(phi)*cos(theta)^2),...
    (-thetadot*psidot*cos(theta)*(Jx-(Jz-Jy)*(cos(phi)^2-sin(phi)^2)));...
    (psidot^2*sin(theta)*cos(theta)*(-Jx+m1*l1^2+m2*l2^2+Jy*sin(phi)^2 + Jz*cos(phi)^2)),...
    (-2*phidot*thetadot*(Jz-Jy)*sin(phi)*cos(phi)-phidot*psidot*cos(theta)*(-Jx+(Jz-Jy)*(cos(phi)^2-sin(phi)^2))):...
    (thetadot^2*(Jz-Jy)*sin(phi)*cos(phi)*sin(theta)-phidot*thetadot*cos(theta)*(Jx+(Jz-Jy)*(cos(phi)^2-sin(phi)^2))),...
    (-2*phidot*psidot*(Jz-Jy)*cos(theta)^2*sin(phi)*cos(phi)+2*thetadot*psidot*sin(theta)*cos(theta)*(Jx-m1*l1^2-m2*l2^2-Jy*sin(phi)^2-Jz*cos(phi)^2))];